# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HealthCareManagement' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
	pod 'Charts'
  # Pods for HealthCareManagement

  target 'HealthCareManagementTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HealthCareManagementUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
